/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import factory.ComponentResizer;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.GraphicsEnvironment;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Ferreira Assis Gomes
 */
public class Home extends javax.swing.JFrame {

    private Dimension dimensao_atual, dimensao_aux;
    private Point ponto_pressionado_na_tela;
    private Point ponto_atual_no_ecran, ponto_restauro;
    private boolean arq;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        dimensao_aux = new Dimension(this.getSize());
        ponto_pressionado_na_tela = new Point();
        ponto_restauro = ponto_atual_no_ecran = this.getLocation();
    }

    private void selecionar_Separador(Component cc) {
        Component[] cm = new Component[]{jPanel14, jPanel15, jPanel16};
        int i = 2;
        for (Component c : cm) {
            if (cc.equals(c)) {
                c.setBackground(new ColorUIResource(240, 240, 240));
                c.setName("S");
                c.getComponentAt(0, 0).setForeground(new ColorUIResource(41, 83, 145));
                ((CardLayout) jPanel33.getLayout()).show(jPanel33, "card" + i);
            } else {
                c.setBackground(new ColorUIResource(41, 83, 145));
                c.setName(null);
                c.getComponentAt(0, 0).setForeground(new ColorUIResource(255, 255, 255));
            }
            i++;
        }
    }

    private void selecionar_Menu(Component cc) {
        Component[] cm = new Component[]{jPanel23, jPanel24, jPanel25, jPanel26, jPanel27, jPanel28, jPanel29, jPanel30, jPanel31, jPanel32};
        for (Component c : cm) {
            if (cc.equals(c)) {
                c.setBackground(new ColorUIResource(0, 44, 99));
                c.setName("S");
            } else {
                c.setBackground(new ColorUIResource(41, 83, 145));
                c.setName(null);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        pnRar = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel26 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel30 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(811, 487));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 83, 145)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(41, 83, 145));
        jPanel4.setPreferredSize(new java.awt.Dimension(809, 30));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel34.setBackground(new java.awt.Color(41, 83, 145));
        jPanel34.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(41, 83, 145));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel34.add(jPanel5);

        jPanel17.setBackground(new java.awt.Color(41, 83, 145));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("F-System # Gestão");
        jLabel24.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel17.add(jLabel24);

        jPanel34.add(jPanel17);

        jPanel7.setBackground(new java.awt.Color(41, 83, 145));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        jPanel10.setBackground(new java.awt.Color(41, 83, 145));
        jPanel10.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/miB.png"))); // NOI18N
        jLabel23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel23MouseMoved(evt);
            }
        });
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        jPanel10.add(jLabel23);

        jPanel7.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(41, 83, 145));
        jPanel11.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ma.png"))); // NOI18N
        jLabel22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel22MouseMoved(evt);
            }
        });
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jPanel11.add(jLabel22);

        jPanel7.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(41, 83, 145));
        jPanel12.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jLabel21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel21MouseMoved(evt);
            }
        });
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel12.add(jLabel21);

        jPanel7.add(jPanel12);

        jPanel34.add(jPanel7);

        jPanel4.add(jPanel34, "card2");

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(41, 83, 145));
        jPanel18.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel18, java.awt.BorderLayout.LINE_START);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("F-System # Gestão");
        jLabel26.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel19.add(jLabel26, java.awt.BorderLayout.CENTER);

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setLayout(new java.awt.GridLayout(1, 0));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mi.png"))); // NOI18N
        jLabel27.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel27MouseMoved(evt);
            }
        });
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });
        jPanel37.add(jLabel27);

        jPanel36.add(jPanel37);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(new java.awt.GridLayout(1, 0));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maP.png"))); // NOI18N
        jLabel28.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel28MouseMoved(evt);
            }
        });
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });
        jPanel38.add(jLabel28);

        jPanel36.add(jPanel38);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setLayout(new java.awt.GridLayout(1, 0));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/closeB.png"))); // NOI18N
        jLabel29.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel29MouseMoved(evt);
            }
        });
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel29MouseExited(evt);
            }
        });
        jPanel39.add(jLabel29);

        jPanel36.add(jPanel39);

        jPanel19.add(jPanel36, java.awt.BorderLayout.EAST);

        jPanel35.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel35, "card3");

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(718, 130));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(41, 83, 145));
        jPanel9.setPreferredSize(new java.awt.Dimension(718, 30));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel13.setBackground(new java.awt.Color(41, 83, 145));
        jPanel13.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arquivo");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        jPanel13.add(jLabel1);

        jPanel9.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(41, 83, 145));
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Página Inicial");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel14.add(jLabel2);

        jPanel9.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(41, 83, 145));
        jPanel15.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inserir");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        jPanel15.add(jLabel3);

        jPanel9.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(41, 83, 145));
        jPanel16.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Design");
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel16.add(jLabel4);

        jPanel9.add(jPanel16);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel33.setLayout(new java.awt.CardLayout());

        jLabel5.setText("Menu Página Inicial");
        jPanel44.add(jLabel5);

        jPanel33.add(jPanel44, "card2");

        jLabel7.setText("Menu Inserir");
        jPanel45.add(jLabel7);

        jPanel33.add(jPanel45, "card3");

        jLabel8.setText("Menu Design");
        jPanel46.add(jLabel8);

        jPanel33.add(jPanel46, "card4");

        jPanel8.add(jPanel33, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel40.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jPanel40.add(jPanel41, "card2");

        jScrollPane2.setViewportView(jPanel40);

        jPanel20.add(jScrollPane2);

        jPanel2.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, "card2");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(867, 531));

        jPanel6.setPreferredSize(new java.awt.Dimension(867, 531));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel21.setBackground(new java.awt.Color(41, 83, 145));
        jPanel21.setPreferredSize(new java.awt.Dimension(150, 372));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel21MouseExited(evt);
            }
        });
        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel22.setBackground(new java.awt.Color(41, 83, 145));
        jPanel22.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel22.setLayout(new java.awt.GridLayout(1, 1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backW1.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel19.setIconTextGap(-5);
        jLabel19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel19MouseMoved(evt);
            }
        });
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        jPanel22.add(jLabel19);

        jPanel21.add(jPanel22);

        jPanel23.setBackground(new java.awt.Color(41, 83, 145));
        jPanel23.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel23.setLayout(new java.awt.GridLayout(1, 1));

        pnRar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnRar.setForeground(new java.awt.Color(240, 240, 240));
        pnRar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new2.png"))); // NOI18N
        pnRar.setText("Novo");
        pnRar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnRar.setIconTextGap(-4);
        pnRar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnRarMouseMoved(evt);
            }
        });
        pnRar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnRarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnRarMouseReleased(evt);
            }
        });
        jPanel23.add(pnRar);

        jPanel21.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(41, 83, 145));
        jPanel24.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel24.setLayout(new java.awt.GridLayout(1, 1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("          Abrir");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel17MouseMoved(evt);
            }
        });
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        jPanel24.add(jLabel17);

        jPanel21.add(jPanel24);

        jPanel25.setBackground(new java.awt.Color(41, 83, 145));
        jPanel25.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel25.setLayout(new java.awt.GridLayout(1, 5));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("          Fechar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        jPanel25.add(jLabel6);

        jPanel21.add(jPanel25);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(120, 1));
        jPanel21.add(jSeparator1);

        jPanel26.setBackground(new java.awt.Color(41, 83, 145));
        jPanel26.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel26.setLayout(new java.awt.GridLayout(1, 1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("          Relatório");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel25.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel25MouseMoved(evt);
            }
        });
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel25MouseReleased(evt);
            }
        });
        jPanel26.add(jLabel25);

        jPanel21.add(jPanel26);

        jPanel27.setBackground(new java.awt.Color(41, 83, 145));
        jPanel27.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel27.setLayout(new java.awt.GridLayout(1, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("          Correio");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });
        jPanel27.add(jLabel9);

        jPanel21.add(jPanel27);

        jPanel28.setBackground(new java.awt.Color(41, 83, 145));
        jPanel28.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel28.setLayout(new java.awt.GridLayout(1, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("          Nuvem");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });
        jPanel28.add(jLabel10);

        jPanel21.add(jPanel28);

        jPanel29.setBackground(new java.awt.Color(41, 83, 145));
        jPanel29.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel29.setLayout(new java.awt.GridLayout(1, 1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("          Definições");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel20MouseMoved(evt);
            }
        });
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel20MouseReleased(evt);
            }
        });
        jPanel29.add(jLabel20);

        jPanel21.add(jPanel29);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(120, 1));
        jPanel21.add(jSeparator2);

        jPanel30.setBackground(new java.awt.Color(41, 83, 145));
        jPanel30.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel30.setLayout(new java.awt.GridLayout(1, 1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("          Suporte Técnico");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel12MouseMoved(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });
        jPanel30.add(jLabel12);

        jPanel21.add(jPanel30);

        jPanel31.setBackground(new java.awt.Color(41, 83, 145));
        jPanel31.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel31.setLayout(new java.awt.GridLayout(1, 1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("          Ajuda");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel13MouseMoved(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });
        jPanel31.add(jLabel13);

        jPanel21.add(jPanel31);

        jPanel32.setBackground(new java.awt.Color(41, 83, 145));
        jPanel32.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel32.setLayout(new java.awt.GridLayout(1, 1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("          Sobre");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel14MouseMoved(evt);
            }
        });
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel14MouseReleased(evt);
            }
        });
        jPanel32.add(jLabel14);

        jPanel21.add(jPanel32);

        jPanel6.add(jPanel21, java.awt.BorderLayout.WEST);

        jPanel42.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jPanel42.add(jPanel43, "card2");

        jPanel6.add(jPanel42, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel6);

        jPanel1.add(jScrollPane1, "card4");

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(869, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel23MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel23MouseMoved

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        //this.setState(Frame.ICONIFIED);
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel22MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel22MouseMoved
    boolean max = false;
    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        dimensao_atual = this.getSize();
        if ((GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().getSize().width != dimensao_atual.width
                && GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().getSize().height != dimensao_atual.height)
                && !max) {
            ponto_restauro = this.getLocation();
            max = true;
            dimensao_aux = dimensao_atual;
            this.setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds());
            jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/re.png")));
            jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reB.png")));
        } else {
            this.setSize(dimensao_aux);
            this.setLocation(ponto_restauro);
            max = false;
            jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maP.png")));
            jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ma.png")));
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseMoved
        evt.getComponent().getParent().setBackground(Color.red);
    }//GEN-LAST:event_jLabel21MouseMoved

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));

    }//GEN-LAST:event_jLabel21MouseExited

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        ponto_atual_no_ecran.x = ponto_atual_no_ecran.x + evt.getX() - ponto_pressionado_na_tela.x;
        ponto_atual_no_ecran.y = ponto_atual_no_ecran.y + evt.getY() - ponto_pressionado_na_tela.y;
        this.setLocation(ponto_atual_no_ecran);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        ponto_pressionado_na_tela.x = evt.getX();
        ponto_pressionado_na_tela.y = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
        }
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
        }
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
        }
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(240, 240, 240));
        }
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(240, 240, 240));
        }
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
            evt.getComponent().setForeground(new ColorUIResource(255, 255, 255));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(240, 240, 240));
        }
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel19MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel19MouseMoved

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        ((CardLayout) jPanel1.getLayout()).show(jPanel1, "card2");
        ((CardLayout) jPanel4.getLayout()).show(jPanel4, "card2");
        jPanel4.setBackground(new ColorUIResource(41, 83, 145));
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
    }//GEN-LAST:event_jLabel19MouseExited

    private void pnRarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRarMouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_pnRarMouseMoved

    private void pnRarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRarMouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_pnRarMouseExited

    private void jLabel17MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel17MouseMoved

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel25MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel25MouseMoved

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel20MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel20MouseMoved

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel12MouseMoved

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel13MouseMoved

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(16, 66, 122));
    }//GEN-LAST:event_jLabel14MouseMoved

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        if (evt.getComponent().getParent().getName() == null) {
            evt.getComponent().getParent().setBackground(new ColorUIResource(41, 83, 145));
        } else {
            evt.getComponent().getParent().setBackground(new ColorUIResource(0, 44, 99));
        }
    }//GEN-LAST:event_jLabel14MouseExited

    private void jPanel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseExited
        //jPanel4.setVisible(!true);
    }//GEN-LAST:event_jPanel21MouseExited

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        ((CardLayout) jPanel1.getLayout()).show(jPanel1, "card4");
        ((CardLayout) jPanel4.getLayout()).show(jPanel4, "card3");
        jPanel4.setBackground(Color.white);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel27MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(215, 229, 245));
    }//GEN-LAST:event_jLabel27MouseMoved

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        evt.getComponent().getParent().setBackground(Color.white);
    }//GEN-LAST:event_jLabel27MouseExited

    private void jLabel28MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseMoved
        evt.getComponent().getParent().setBackground(new ColorUIResource(215, 229, 245));
    }//GEN-LAST:event_jLabel28MouseMoved

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        dimensao_atual = this.getSize();
        if ((GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().getSize().width != dimensao_atual.width
                && GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().getSize().height != dimensao_atual.height)
                && !max) {
            ponto_restauro = this.getLocation();
            max = true;
            dimensao_aux = dimensao_atual;
            this.setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds());
            jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/re.png")));
            jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reB.png")));
        } else {
            this.setSize(dimensao_aux);
            this.setLocation(ponto_restauro);
            max = false;
            jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maP.png")));
            jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ma.png")));
        }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        evt.getComponent().getParent().setBackground(Color.white);
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel29MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseMoved
        evt.getComponent().getParent().setBackground(Color.red);
    }//GEN-LAST:event_jLabel29MouseMoved

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseExited
        evt.getComponent().getParent().setBackground(Color.white);
    }//GEN-LAST:event_jLabel29MouseExited

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        selecionar_Separador(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        selecionar_Separador(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        selecionar_Separador(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel4MouseReleased

    private void pnRarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRarMouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_pnRarMouseReleased

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel17MouseReleased

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel25MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel25MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel12MouseReleased

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased
        selecionar_Menu(evt.getComponent().getParent());
    }//GEN-LAST:event_jLabel14MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println("Erro LookAndFeel: " + ex.getMessage());
        }
        java.awt.EventQueue.invokeLater(() -> {
            new Home().mostrar();
        });
    }

    private void mostrar() {
        ComponentResizer cr = new ComponentResizer();
        cr.registerComponent(this);
        this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pnRar;
    // End of variables declaration//GEN-END:variables
}
